language: node_js
node_js:
  - '0.10'
after_script:
  - node app.js
  - mv cv.html _cv.html
  - mv cv.css _cv.css
  - mv cv.pdf _cv.pdf
  - git config credential.helper "store --file=.git/credentials"
  - git config --global user.email "melena.art@gmail.com"
  - git config --global user.name "millasa"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git remote set-url origin https://github.com/millasa/cv-generator.git
  - git remote set-branches --add origin gh-pages  
  - git fetch
  - git checkout gh-pages
  - git rm -rf .
  - mv _cv.html cv.html
  - mv _cv.css cv.css
  - mv _cv.pdf cv.pdf
  - git add cv.html
  - git add cv.css
  - git add cv.pdf
  - git commit -m "Travis build"
  - git push origin gh-pages
env:
  global:
    secure: ZawwJCG3uJ+D5BhQbSvNltSC5n1znFKaWtx0mJHSTTPd5lVu2e2wNH4nJs7L4IHbmhUoh5ielOvgG8tV+zh11F9s0/bfBak3NcuNpNbCZxVLeAIfD/n07KGYWaQXAz+QMDJ
